# Configuração de implantação para o Netlify
[build]
  command = "npm run build"
  publish = "dist"

# Configuração para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200